---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: npm-config-pv
  labels:
    app.kubernetes.io/part-of: arr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/gluster/appdata/Nginx-Proxy-Manager-Official
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: npm-config-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  namespace: media
  labels:
    app.kubernetes.io/name: npm
    app.kubernetes.io/part-of: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: npm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: npm
    spec:
      containers:
        - name: npm
          image: jc21/nginx-proxy-manager:latest
          ports:
            - containerPort: 80
            - containerPort: 81
            - containerPort: 443
          env:
            - name: TZ
              value: America/Denver
          volumeMounts:
            - name: config
              mountPath: /data
            - name: ssl
              mountPath: /etc/letsencrypt
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: npm-config
        - name: ssl
          hostPath:
            path: /mnt/gluster/appdata/Nginx-Proxy-Manager-Official/letsencrypt
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
  namespace: media
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: npm
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: admin
      port: 81
      targetPort: 81
    - name: https
      port: 443
      targetPort: 443
