apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/appdata/audiobookshelf
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-audiobooks-pv
spec:
  capacity:
    storage: 5Ti # Adjust as needed
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/media/audiobooks
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-podcasts-pv
spec:
  capacity:
    storage: 1Ti # Adjust as needed
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/media/podcasts
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-metadata-pv
spec:
  capacity:
    storage: 2Gi # Metadata can grow
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/appdata/audiobookshelf-metadata
