# k3s/apps/audiobookshelf.yaml
---
# PVC for application configuration and database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-shared
  resources:
    requests:
      storage: 2Gi
---
# PVC for metadata (book covers, author images, etc.)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-shared
  resources:
    requests:
      storage: 10Gi
---
# Deployment for the application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: default
  labels:
    app: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:latest
        ports:
        - containerPort: 80
        volumeMounts:
        # Mount for config/database
        - name: config
          mountPath: /config
        # Mount for metadata
        - name: metadata
          mountPath: /metadata
        # Mount your one big media drive for the audiobook files
        - name: audiobooks
          mountPath: /audiobooks
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: audiobookshelf-config-pvc
      - name: metadata
        persistentVolumeClaim:
          claimName: audiobookshelf-metadata-pvc
      # This attaches your main media PVC
      - name: audiobooks
        persistentVolumeClaim:
          claimName: media-pvc
---
# Service for internal networking
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: default
spec:
  selector:
    app: audiobookshelf
  ports:
  - name: http
    port: 80
    targetPort: 80
