# k3s/apps/plex.yaml
---
# PVC for Plex's configuration and metadata library
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-shared
  resources:
    requests:
      storage: 50Gi
---
# Service to expose Plex on a port on every node
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
spec:
  type: NodePort # This is the key change
  selector:
    app: plex
  ports:
    - name: http-plex
      port: 32400
      targetPort: 32400
      protocol: TCP
---
# Deployment for the Plex application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: default
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      # We no longer need hostNetwork or dnsPolicy
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Denver"
        - name: VERSION
          value: "docker"
        - name: PLEX_CLAIM
          value: claim-6UZPD5xX1uVSrVEZCDxt
        ports:
        - containerPort: 32400
        volumeMounts:
        - name: config
          mountPath: /config
        - name: transcode
          mountPath: /transcode
        - name: media
          mountPath: /media
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config-pvc
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
      - name: transcode
        emptyDir: {}
