# k3s/apps/radarr.yaml
---
# PVC for Radarr's configuration and database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-shared
  resources:
    requests:
      storage: 5Gi
---
# Deployment for the Radarr application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: default
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Denver"
        ports:
        - containerPort: 7878
        volumeMounts:
        # Mount for Radarr's config
        - name: config
          mountPath: /config
        # Mount your one big media drive.
        # Radarr will access both downloads and the final movie library from here.
        - name: media
          mountPath: /media
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config-pvc
      # This attaches your main media PVC to the pod
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
---
# Service for internal networking
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: default
spec:
  selector:
    app: radarr
  ports:
  - name: http
    port: 7878
    targetPort: 7878
