additionalArguments:
  - "--entryPoints.web.address=:80"
  - "--entryPoints.websecure.address=:443"
  - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
  - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
  - "--certificatesresolvers.cloudflare.acme.email=your@email.com"
  - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"
  - "--api.dashboard=true"
  - "--log.level=DEBUG"

env:
  - name: CF_API_EMAIL
    value: your@email.com
  - name: CF_DNS_API_TOKEN
    value: your_cloudflare_api_token

ports:
  web:
    port: 80
    expose: true
  websecure:
    port: 443
    expose: true

service:
  type: LoadBalancer

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
