additionalArguments:
  - --api=true
  - --api.dashboard=true
  - --api.insecure=true
  - --accesslog=true
  - --accesslog.format=json
  - --log.level=DEBUG

ports:
  traefik:
    port: 9000
    expose:
      default: true
    exposedPort: 9000
    protocol: TCP

  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    protocol: TCP

  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP

service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: 192.168.86.240

ingressClass:
  enabled: true
  isDefaultClass: true
