apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: linuxmint-vm
  namespace: vm-lab
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: linuxmint-vm
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cdromiso
              cdrom:
                bus: sata
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - port: 5900
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: mint-vm-pvc
        - name: cdromiso
          containerDisk:
            image: kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: mint
              chpasswd: { expire: False }
              ssh_pwauth: True
