apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/appdata/sonarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tv-pv
spec:
  capacity:
    storage: 10Ti # Adjust size as needed for your TV library
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/media/tv # A dedicated folder for TV shows
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-downloads-pv
spec:
  capacity:
    storage: 5Ti # Must match the size of the shared downloads folder PV
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/media/media_holder # The same downloads folder SABnzbd uses
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-anime-pv
spec:
  capacity:
    storage: 5Ti # Adjust size as needed
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/media/anime # This is the new folder on your node
