apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-pv
spec:
  capacity:
    storage: 1Gi # Prowlarr config is small
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/appdata/prowlarr
