apiVersion: apps/v1
kind: Deployment
metadata:
  name: huntarr
  labels:
    app: huntarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huntarr
  template:
    metadata:
      labels:
        app: huntarr
    spec:
      containers:
        - name: huntarr
          image: huntarr/huntarr:latest
          ports:
            - containerPort: 9705
          env:
            - name: PORT
              value: "9705"
            - name: HUNTARR_PORT
              value: "9705"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: huntarr-config

---
apiVersion: v1
kind: Service
metadata:
  name: huntarr
  namespace: default
spec:
  selector:
    app: huntarr
  ports:
    - protocol: TCP
      port: 9705
      targetPort: 9705
  type: ClusterIP

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: huntarr
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`huntarr.rahl.cc`)
      kind: Rule
      services:
        - name: huntarr
          port: 9705
  tls:
    certResolver: cloudflare

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huntarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
