---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  # This is the file cloudflared reads at /etc/cloudflared/config.yaml
  config.yaml: |
    # Replace with your real Tunnel ID (the one that matches your credentials.json)
    tunnel: <YOUR_TUNNEL_ID>
    credentials-file: /etc/cloudflared/credentials.json

    # One rule per hostname -> in-cluster Service (ClusterIP)
    # NOTE: Ports below are the common defaults. If your Service uses a different port,
    # we’ll adjust after a quick check.
    ingress:
      # ===== rahl.cc =====
      - hostname: abs.rahl.cc              # Audiobookshelf (alias 1)
        service: http://audiobookshelf.media.svc.cluster.local:80
      - hostname: audiobookshelf.rahl.cc   # Audiobookshelf (alias 2)
        service: http://audiobookshelf.media.svc.cluster.local:80
      - hostname: vault.rahl.cc            # Vaultwarden
        service: http://vaultwarden.media.svc.cluster.local:80
      - hostname: actual.rahl.cc           # Actual Budget
        service: http://actual.media.svc.cluster.local:5006
      - hostname: sonarr.rahl.cc
        service: http://sonarr.media.svc.cluster.local:8989
      - hostname: radarr.rahl.cc
        service: http://radarr.media.svc.cluster.local:7878
      - hostname: prowlarr.rahl.cc
        service: http://prowlarr.media.svc.cluster.local:9696
      - hostname: huntarr.rahl.cc
        service: http://huntarr.media.svc.cluster.local:8000
      - hostname: overseerr.rahl.cc
        service: http://overseerr.media.svc.cluster.local:5055
      - hostname: sabnzbd.rahl.cc
        service: http://sabnzbd.media.svc.cluster.local:8080
      - hostname: obsidian.rahl.cc
        service: http://obsidian.media.svc.cluster.local:3000
      - hostname: metube.rahl.cc
        service: http://metube.media.svc.cluster.local:8081
      - hostname: dumbassets.rahl.cc
        service: http://dumbassets.media.svc.cluster.local:8080
      - hostname: remote.rahl.cc           # Apache Guacamole
        service: http://guacamole.guacamole.svc.cluster.local:8080
      - hostname: jellyfin.rahl.cc
        service: http://jellyfin.media.svc.cluster.local:8096

      # ===== fractal-financial.com =====
      - hostname: abs.fractal-financial.com
        service: http://audiobookshelf.media.svc.cluster.local:80
      - hostname: audiobookshelf.fractal-financial.com
        service: http://audiobookshelf.media.svc.cluster.local:80
      - hostname: vault.fractal-financial.com
        service: http://vaultwarden.media.svc.cluster.local:80
      - hostname: actual.fractal-financial.com
        service: http://actual.media.svc.cluster.local:5006
      - hostname: sonarr.fractal-financial.com
        service: http://sonarr.media.svc.cluster.local:8989
      - hostname: radarr.fractal-financial.com
        service: http://radarr.media.svc.cluster.local:7878
      - hostname: prowlarr.fractal-financial.com
        service: http://prowlarr.media.svc.cluster.local:9696
      - hostname: huntarr.fractal-financial.com
        service: http://huntarr.media.svc.cluster.local:8000
      - hostname: overseerr.fractal-financial.com
        service: http://overseerr.media.svc.cluster.local:5055
      - hostname: sabnzbd.fractal-financial.com
        service: http://sabnzbd.media.svc.cluster.local:8080
      - hostname: obsidian.fractal-financial.com
        service: http://obsidian.media.svc.cluster.local:3000
      - hostname: metube.fractal-financial.com
        service: http://metube.media.svc.cluster.local:8081
      - hostname: dumbassets.fractal-financial.com
        service: http://dumbassets.media.svc.cluster.local:8080
      - hostname: remote.fractal-financial.com
        service: http://guacamole.guacamole.svc.cluster.local:8080
      - hostname: jellyfin.fractal-financial.com
        service: http://jellyfin.media.svc.cluster.local:8096

      # Catch-all (404) for anything not matched above
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      serviceAccountName: cloudflared
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2023.10.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
          # Optional: small readiness probe so we know the sidecar is healthy
          readinessProbe:
            exec:
              command: ["sh","-lc","cloudflared --version >/dev/null 2>&1"]
            initialDelaySeconds: 5
            periodSeconds: 30
          volumeMounts:
            - name: config-volume
              mountPath: /etc/cloudflared/config.yaml
              subPath: config.yaml
            - name: credentials-volume
              mountPath: /etc/cloudflared/credentials.json
              subPath: credentials.json
      volumes:
        - name: config-volume
          configMap:
            name: cloudflared-config
        - name: credentials-volume
          secret:
            secretName: cloudflared-credentials
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
