tunnel: bb4c24f4-7fff-46b5-9548-517a288415ed
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: jellyfin.rahl.cc
    service: http://jellyfin.media.svc.cluster.local:8096

  - hostname: overseerr.rahl.cc
    service: http://overseerr.default.svc.cluster.local:5055

  - hostname: huntarr.rahl.cc
    service: http://huntarr.default.svc.cluster.local:9705

  - hostname: radarr.rahl.cc
    service: http://radarr.default.svc.cluster.local:7878

  - hostname: sonarr.rahl.cc
    service: http://sonarr.default.svc.cluster.local:8989

  - hostname: prowlarr.rahl.cc
    service: http://prowlarr.default.svc.cluster.local:9696

  - hostname: sabnzbd.rahl.cc
    service: http://sabnzbd.default.svc.cluster.local:8080

  - hostname: vault.rahl.cc
    service: http://vaultwarden.default.svc.cluster.local:80

  - hostname: vault.fractal-financial.com
    service: http://vaultwarden.default.svc.cluster.local:80

  - hostname: audiobookshelf.rahl.cc
    service: http://audiobookshelf.default.svc.cluster.local:80

  - hostname: metube.rahl.cc
    service: http://metube.default.svc.cluster.local:8081

  - hostname: obsidian.rahl.cc
    service: http://obsidian.default.svc.cluster.local:443

  - service: http_status:404
