name: Update Latest Snapshot URL

on:
  push:
    branches:
      - main # Or 'master' if that's your default branch
    paths:
      - 'snapshots/**'
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-latest-file-url:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Give the workflow permission to write to the repo
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Find latest file and create pointer
        run: |
          # Go into the snapshots directory
          cd snapshots
          
          # Find the most recently modified file/folder
          LATEST_FILE=$(ls -t | head -n 1)
          
          # Construct the full raw URL
          RAW_URL="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/snapshots/${LATEST_FILE}"
          
          # Go back to the root and write the URL to latest.txt
          cd ..
          echo $RAW_URL > latest.txt
          
          echo "Latest snapshot URL is: $RAW_URL"

      - name: Commit and push latest.txt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update latest snapshot URL"
          file_pattern: "latest.txt"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
