apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/appdata/radarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-movies-pv
spec:
  capacity:
    storage: 10Ti # Adjust size as needed for your movie library
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/media/movies # A dedicated folder for movies
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-downloads-pv
spec:
  capacity:
    storage: 5Ti # Must match the size of the shared downloads folder PV
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/media/media_holder # The same downloads folder SABnzbd uses
